spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://192.168.117.134:8084
  zipkin:
      base-url: http://192.168.117.134:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.117.134:8761/eureka/

zuul:
  routes:
    api-b:
      path: /api/b/**
      serviceId: itoken-admin-feign

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info