spring:
  application:
    name: itoken-redis-sentinel
  boot:
    admin:
      client:
        url: http://192.168.117.134:8084
  zipkin:
    base-url: http://192.168.117.134:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: master
      nodes: 192.168.117.139:26379,192.168.117.139:26380,192.168.117.139:26381



server:
  port: 8602



eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.117.134:8761/eureka/,http://192.168.117.134:8861/eureka/,http://192.168.117.134:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
