spring:
  application:
    name: itoken-service-upload
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: master
      nodes: localhost:26379,localhost:26380,localhost:26381



server:
  port: 8604

fastdfs.base.url: http://localhost:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: localhost:22122


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8861/eureka/,http://localhost:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
