version: '3.1'
services:
  itoken-zuul:
    restart: always
    image: 192.168.117.133:5000/itoken-zuul
    container_name: itoken-zuul
    ports:
      - 8769:8769
    networks:
      - zuul-network

networks:
  zuul-network: